[package]
name = "push-fastcdc"
version = "0.1.0"
edition = "2024"
exclude = ["test/*"]

[dev-dependencies]
criterion = "0.6.0"
fastcdc = "3.2.1"
fastrand = "2.3.0"
md-5 = "0.10.5"

[[bench]]
name = "basic"
harness = false
