[package]
name = "crucible-host-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
derive-where = "1.6.0"
scopeguard = "1.2.0"
smallbox = "0.8.8"
smol = "2.0.2"
thiserror = "2.0.16"
