[package]
name = "crucible-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bytemuck = { version = "1.23.1", features = ["min_const_generics"] }
derive-where = "1.5.0"
late-struct = "0.1.0"
wasmtime = "34.0.1"
