[workspace]
resolver = "2"
members = [
    "guest/crucible",
    "guest/demo-game",
    "host/client",
    "host/protocol",
    "host/renderer",
    "host/server",
    "host/wasmall",
    "host/wasmlink-wasmtime",
    "shared/crucible-abi",
    "shared/wasmlink",
]

[workspace.dependencies]
crucible = { path = "guest/crucible" }
crucible-abi = { path = "shared/crucible-abi" }
crucible-renderer = { path = "host/renderer" }
wasmlink = { path = "shared/wasmlink" }
wasmlink-wasmtime = { path = "host/wasmlink-wasmtime" }

[workspace.dependencies.arid]
git = "https://github.com/Radbuglet/arid.git"
rev = "8f35a74e1ac22445848a40747583ab2b29aeec5a"

[workspace.dependencies.arid-entity]
git = "https://github.com/Radbuglet/arid.git"
rev = "8f35a74e1ac22445848a40747583ab2b29aeec5a"

[profile.dev.package."*"]
opt-level = 2
