[workspace]
resolver = "2"
members = [
    "guest/crucible-abi",
    "guest/crucible",
    "guest/demo-game",
    "host/client",
    "host/protocol",
    "host/server",
    "utils/glacee",
    "utils/renderer",
    "utils/wasmlink-wasmtime",
    "utils/wasmlink",
    "utils/wasmall",
    "utils/push-fastcdc",
]

[workspace.dependencies]
crucible = { path = "guest/crucible" }
crucible-abi = { path = "guest/crucible-abi" }
crucible-protocol = { path = "host/protocol" }
crucible-renderer = { path = "utils/renderer" }
wasmlink = { path = "utils/wasmlink" }
wasmlink-wasmtime = { path = "utils/wasmlink-wasmtime" }
push-fastcdc = { path = "utils/push-fastcdc" }

[workspace.dependencies.arid]
git = "https://github.com/Radbuglet/arid.git"
rev = "8f35a74e1ac22445848a40747583ab2b29aeec5a"

[workspace.dependencies.arid-entity]
git = "https://github.com/Radbuglet/arid.git"
rev = "8f35a74e1ac22445848a40747583ab2b29aeec5a"

[workspace.dependencies.quinn]
version = "0.11.8"
default-features = false
# Use `aws-lc-rs` because that's what `librice` favors.
#  We don't use the `platform-verifier` feature directly because we instantiate the
#  `rustls-platform-verifier` verifier directly.
features = ["bloom", "log", "runtime-tokio", "rustls-aws-lc-rs"]

[profile.dev.package."*"]
opt-level = 2
