[workspace]
resolver = "2"
members = ["guest/crucible", "guest/demo-game", "host/client", "host/renderer"]

[workspace.dependencies]
crucible = { path = "guest/crucible" }
crucible-renderer = { path = "host/renderer" }

[profile.dev.package."*"]
opt-level = 2
