[package]
name = "demo-game"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.23.1"
crucible = { workspace = true }
cruise = { version = "0.1.0", path = "../cruise" }
glam = "0.30.4"
image = { version = "0.25.6", default-features = false, features = ["png"] }
