[package]
name = "crt-cafs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
async-tempfile = "0.5.0"
blake3 = "1.5.0"
derive-where = "1.2.7"
hashbrown = "0.14.3"
log = "0.4.20"
rustc-hash = "1.1.0"
sled = "0.34.7"
tokio = { version = "1.36.0", features = ["sync", "io-util"] }
