[package]
name = "wasmall"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
blake3 = "1.8.2"
leb128 = "0.2.5"
push-fastcdc.workspace = true
rustc-hash = "2.1.1"
smallvec = "1.15.1"
wasmparser = "0.238.0"

[dev-dependencies]
humansize = "2.1.3"
