[package]
name = "crucible-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bytemuck = { version = "1.23.1", features = ["min_const_generics"] }
crevice = "0.18.0"
glam = "0.30.4"
wgpu = "25.0.2"

[dev-dependencies]
futures = "0.3.31"
winit = "0.30.11"
