[package]
name = "crucible-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bytemuck = { version = "1.23.1", features = ["min_const_generics"] }
glam = "0.30.4"
wgpu = "25.0.2"
