[package]
name = "wasmlink"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.23.1", features = ["derive"] }
cfgenius = "0.1.1"
derive-where = "1.5.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
thunderdome = "0.6.1"
