[package]
name = "wasmall"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
blake3 = "1.5.0"
leb128 = "0.2.5"
log = "0.4.20"
rustc-hash = "1.1.0"
wasm-encoder = "0.41.0"
wasmparser = "0.121.0"

[dev-dependencies]
env_logger = "0.11.1"
