[package]
name = "crt-marshal"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.14.3", features = ["derive"] }
wasmtime = { version = "18.0.2", default-features = false, optional = true }

[features]
default = ["alloc"]
alloc = []
wasmtime = ["dep:wasmtime"]
