[package]
name = "crucible"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.1"
bytemuck = { version = "1.23.1", features = ["min_const_generics"] }
glam = "0.30.4"
scopeguard = "1.2.0"
