[package]
name = "cruise"
version = "0.1.0"
edition = "2024"

[dependencies]
crucible.workspace = true
derive-where = "1.5.0"
glam = "0.30.4"

[dependencies.arid]
git = "https://github.com/Radbuglet/arid.git"
rev = "de2862f334a19aaf45d7741349e37d21912fe292"
